name: SimpleTrash
main: me.hoot215.simpletrash.SimpleTrash
version: 1.2
author: Hoot215
permissions:
  simpletrash.trash:
    description: "Gives access to the command '/trash'"
    default: true
commands:
  trash:
    description: "Displays a trash can"
    permission: simpletrash.trash
    permission-message: "§cYou don't have permission to use that command!"
    usage: "§e/<command>"
